### ISSUE TITLE
Connection refused error, randomly.

### ISSUE THREAD

**Issue by benjaminestes** [benjaminestes/pyscape-client#25]
While getting numerous URLs using the CLI:

```
Traceback (most recent call last):
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyscape-batch", line 88, in <module>
    sys.exit(main())
  File "pyscape-batch", line 81, in main
    data.extend(p.batch_url_metrics(batch).json())
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/pyscape_client-2015.02b2-py3.4.egg/pyscape/endpoints.py", line 49, in batch_url_metrics
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/pyscape_client-2015.02b2-py3.4.egg/pyscape/api.py", line 55, in post
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/requests-2.5.3-py3.4.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by benjaminestes** [comment]
Nothing fundamentally wrong with the library, just need to either/both:

1. Add error handling to the library.
2. Add error handling to the CLI.

Pretty common use case, so definitely worth pursuing.
