### ISSUE TITLE
Error writing file after data collected

### ISSUE THREAD

**Issue by benjaminestes** [benjaminestes/pyscape-client#26]
From GK's input file:

```
Traceback (most recent call last):
  File "/Users/benjamin/.virtualenvs/test5/bin/pyscape", line 5, in <module>
    pkg_resources.run_script('pyscape-client==2015.02b2', 'pyscape')
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/pkg_resources.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/pyscape_client-2015.02b2-py3.4.egg/EGG-INFO/scripts/pyscape", line 85, in <module>
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/pyscape_client-2015.02b2-py3.4.egg/EGG-INFO/scripts/pyscape", line 82, in main
  File "/Users/benjamin/.virtualenvs/test5/lib/python3.4/site-packages/pyscape_client-2015.02b2-py3.4.egg/EGG-INFO/scripts/pyscape", line 48, in write_csv
TypeError: string indices must be integers
```

**Comment by benjaminestes** [comment]
Fixed with generic try/except loop. Does anyone know what went wrong here?
